# Generated by Django 4.2.11 on 2024-05-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0003_remove_cars_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='carprices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrental.carprice'),
        ),
    ]
