# Generated by Django 4.2.11 on 2024-05-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0004_cars_carprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='carrental.cars'),
        ),
    ]
