# Generated by Django 4.2.11 on 2024-05-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0005_review_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secount_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='static/users/img')),
                ('pasport', models.ImageField(blank=True, null=True, upload_to='static/users/pasport')),
                ('prava', models.ImageField(blank=True, null=True, upload_to='static/users/prava')),
                ('review', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='carrental.review')),
            ],
        ),
    ]
