# Generated by Django 4.2.11 on 2024-05-02 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0007_remove_carrentai_review_review_carrentai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carprice',
            old_name='name',
            new_name='price_1',
        ),
        migrations.AddField(
            model_name='carprice',
            name='price_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carprice',
            name='price_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='carrentai',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrentai', to='carrental.carrentai'),
        ),
    ]
