# Generated by Django 4.2.11 on 2024-05-02 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0008_rename_name_carprice_price_1_carprice_price_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='carmodels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carmodels', to='carrental.carmodels'),
        ),
        migrations.RemoveField(
            model_name='cars',
            name='carprices',
        ),
        migrations.AlterField(
            model_name='cars',
            name='caryear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caryear', to='carrental.caryear'),
        ),
        migrations.AddField(
            model_name='cars',
            name='carprices',
            field=models.ManyToManyField(blank=True, null=True, related_name='carprices', to='carrental.carprice'),
        ),
    ]
