# Generated by Django 4.2.11 on 2024-05-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0009_alter_cars_carmodels_remove_cars_carprices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='carprices',
            field=models.ManyToManyField(blank=True, related_name='carprices', to='carrental.carprice'),
        ),
    ]
