# Generated by Django 4.2.11 on 2024-05-02 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0010_alter_cars_carprices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='carprices',
        ),
        migrations.AddField(
            model_name='cars',
            name='carprices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carprices', to='carrental.carprice'),
        ),
    ]
