# Generated by Django 4.2.11 on 2024-05-07 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrental', '0011_remove_cars_carprices_cars_carprices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrentai',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='carrentai',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='carrentai',
            name='secount_name',
        ),
        migrations.AddField(
            model_name='carrentai',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
