# Generated by Django 4.2.11 on 2024-05-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0012_remove_carrentai_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentai',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
