# Generated by Django 4.2.11 on 2024-05-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0014_alter_carrentai_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil1', models.CharField(max_length=100)),
                ('manzil2', models.CharField(max_length=100)),
                ('sana1', models.DateField()),
                ('sana2', models.DateField()),
                ('vaqt', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='carrental.booking'),
        ),
    ]
