# Generated by Django 4.2.11 on 2024-05-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0015_booking_review_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vaqt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
