# Generated by Django 4.2.11 on 2024-05-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0016_alter_booking_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vaqt',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
