# Generated by Django 4.2.11 on 2024-05-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0017_alter_booking_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentai',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
