# Generated by Django 4.2.11 on 2024-05-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0018_alter_carrentai_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_comentary',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('berildi', 'Berildi'), ('rad etildi', 'Rad etildi')], default='yangi', max_length=10, null=True),
        ),
    ]
