# Generated by Django 4.2.11 on 2024-05-13 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrental', '0019_review_is_comentary_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_comentary',
        ),
        migrations.AlterField(
            model_name='carrentai',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
