# Generated by Django 4.2.11 on 2024-05-13 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0023_review_is_comentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='carrentai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrentai', to='carrental.carrentai'),
        ),
    ]
