# Generated by Django 4.2.11 on 2024-05-13 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrental', '0024_alter_review_carrentai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentai',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='carrentai',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='carrentai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrentai', to='carrental.carrentai'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('berildi', 'Berildi'), ('qaytarildi', 'Qaytarildi'), ('rad etildi', 'Rad etildi')], default='yangi', max_length=10, null=True),
        ),
    ]
