# Generated by Django 4.2.11 on 2024-05-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0025_alter_carrentai_phone_alter_carrentai_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manzil1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manzil2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='manzil1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrental.manzil1'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='manzil2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrental.manzil2'),
        ),
    ]
