# Generated by Django 4.2.11 on 2024-05-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0027_alter_booking_manzil1_alter_booking_manzil2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='manzil1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='manzil2',
            field=models.CharField(max_length=100),
        ),
    ]
